ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      bundle install --without production &&
      rails db:migrate
    command: >
      rails server -b=0.0.0.0
github:
    prebuilds:
        pullRequestsFromForks: true